import requests
import time

API_KEY = "sk-9e2e832e851c4ec8b27234e8b08363bf"  # 在 GrsAi 后台生成的 key

# 海外用户 Host：
#HOST = "https://api.grsai.com"
# 国内直连用户可替换为：
HOST = "https://grsai.dakka.com.cn"


def create_video():
    url = f"{HOST}/v1/video/sora-video"

    payload = {
        "model": "sora-2",
        "prompt": "The AI host holds the microphone and asks an AI-generated human, 'Do you know you were generated by AI?'",
        "aspectRatio": "16:9",
        "duration": 25,
        "size": "small"
    }

    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {API_KEY}",
    }

    resp = requests.post(url, json=payload, headers=headers)
    print("创建任务返回：", resp.text)

    if resp.status_code != 200:
        return None

    return resp.json()


def get_result(task_id):
    url = f"{HOST}/v1/draw/result"
    payload = {"task_id": task_id}

    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {API_KEY}",
    }

    resp = requests.post(url, json=payload, headers=headers)
    print("查询结果：", resp.text)
    return resp.json()


if __name__ == "__main__":
    # Step 1: 创建视频
    task_resp = create_video()
    if not task_resp or "task_id" not in task_resp:
        print("创建任务失败")
        exit()

    task_id = task_resp["task_id"]
    print("任务 ID:", task_id)

    # Step 2: 等待 3 秒后查询（可按需调整）
    time.sleep(3)

    # Step 3: 查询视频生成进度/结果
    get_result(task_id)
