FROM openjdk:11.0.15-slim-buster
WORKDIR /app/
COPY arthas-tunnel-server-3.6.7-fatjar.jar /app/app.jar
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && mkdir /app/data && mkdir /app/logs

CMD ["sh","-c","java -jar -server $JAVA_OPTS /app/app.jar $PARAMS"]

